version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=backlog
    ports:
      - 5432:5432
    restart: always

  web:
    build: .
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8080
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=
    depends_on:
      - db

volumes:
  db:
    driver: local
