version: "3.8"

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    command: make serve

  frontend:
    build: ./services/frontend
    volumes:
      - "./services/frontend:/app"
      - "/app/node_modules"
    ports:
      - 8080:8080
    command: npm run dev

volumes:
  db:
    driver: local
