version: '3.7'

services:
  web:
    build: .
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:80
    environment:
      - POSTGRES_SERVER=172.22.0.2:5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=backlog-app
    depends_on:
      - db

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=backlog-app
    ports:
      - 6000:5432

volumes:
  postgres_data:
