"""add_tags_and_game

Revision ID: a116a1a3ad5c
Revises: a4625423fdb2
Create Date: 2022-12-11 04:17:42.400001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a116a1a3ad5c'
down_revision = 'a4625423fdb2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backlog_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('required_time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backlog_game_id'), 'backlog_game', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_tags_reference_table',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('tags.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['backlog_game.id'], ),
    sa.ForeignKeyConstraint(['tags.id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_tags_reference_table')
    op.drop_table('tags')
    op.drop_index(op.f('ix_backlog_game_id'), table_name='backlog_game')
    op.drop_table('backlog_game')
    # ### end Alembic commands ###
