"""add_tags_and_game

Revision ID: a4625423fdb2
Revises: c0e596a63225
Create Date: 2022-12-11 04:13:13.807175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4625423fdb2'
down_revision = 'c0e596a63225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
