"""add_tags_and_game

Revision ID: 7e2f8af5d0c7
Revises: 8ec94514d842
Create Date: 2022-12-11 04:26:27.173380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e2f8af5d0c7'
down_revision = '8ec94514d842'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
