"""1

Revision ID: bdcb96007780
Revises: 8b979a32ad09
Create Date: 2023-02-14 23:17:30.364832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcb96007780'
down_revision = '8b979a32ad09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backlog_game', sa.Column('users_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'backlog_game', 'users', ['users_id'], ['id'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'backlog_game', type_='foreignkey')
    op.drop_column('backlog_game', 'users_id')
    # ### end Alembic commands ###
