
name: Tests and linter
on: push
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.4, 3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run check
        run: |
          make check
      - name: Collect coverage
        run: |
          make coverage-report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
