
name: Tests and linter
on: push
jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: ./services/backend
        run: |
          pip install poetry
          make install

      - name: Apply migrations
        working-directory: ./services/backend
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_SERVER: 0.0.0.0:5432
          POSTGRES_DB: ''
        run: |
          make migrate

      - name: Run check
        working-directory: ./services/backend
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_SERVER: 0.0.0.0:5432
          POSTGRES_DB: ''
        run: |
          make check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./services/app/coverage.xml
          fail_ci_if_error: true
